### ISSUE TITLE
p:calendar doesn't show button with BootsFaces 0.8.0 and PrimeFaces 5.3

### ISSUE THREAD

**Issue by nokiajavi** [TheCoder4eu/BootsFaces-OSP#324]
When I use BootsFaces 0.8.0 and PrimeFaces 5.3 the component p:calendar does not show the button with option showOn button.

Example:
```xml
<p:calendar value=#{listForm.date}" mode="popup" size="8" showOn="button" />
```

With BootsFaces 0.7.0 it works correctly. Higher versions fails.

**Comment by stephanrauh** [comment]
I didn't manage to reproduce your error. What precisely does not work? I've tried both BootsFaces 0.8.0 and 0.8.2-SNAPSHOT. When I click on the icon, the calendar shows as expected.

```xml
<p:outputLabel for="issue327" value="Issue 327" />
<p:calendar value="#{calendarView.date3}" mode="popup" size="8" showOn="button" id="issue327"/
```

![image](https://cloud.githubusercontent.com/assets/3045767/13728197/46b55154-e910-11e5-923f-f5ce072ecc22.png)

**Comment by nokiajavi** [comment]
When I start the app , I get this warning
WARNING: JSF1064: Unable to find or serve resource, css/default/icons.css, from library, bsf.

**Comment by zhedar** [comment]
While exploring the PrimeFaces 6.0 issues I just found https://github.com/primefaces/primefaces/issues/1256. Maybe that's the one solving your problem. 6.0RC1 is now available. 
@nokiajavi  Maybe you can check that out and we can close this issue?

**Comment by nokiajavi** [comment]
Hi!


I have included the new version of PrimeFaces , there is a problem and I do not load the file primefaces.css . Surely I have a problem with any filter settings .
If it is of interest , I have created the project with AppFuse
Greetings and thanks

**Comment by zhedar** [comment]
Could you mention, which problem actually? This may be a PrimeFaces issue then.

**Comment by nokiajavi** [comment]
I created the project with AppFuse , including JSF and Primefaces , Bootfaces , Omnifaces , Spirng ...
Currently I have PrimeFaces bootfaces 5.3 and 0.0.7 and I have no problems.
By including a version higher than 0.0.7 bootfaces errors are generated across the web . The most common is that you can not load the css PrimeFaces .

I tried to solve errors in the footsteps of its web , with resourcehandler of omnifaces , but still does not load the .css

As I start the app , indicating RESNOTFOUND.xhtml navigation fails , the inability to load some .css etc ..

**Comment by zhedar** [comment]
With the current information it's quite hard to near impossible to diagnose the problem.
Therefore I have some additional questions:
* Did you test the current 0.8.2-SNAPSHOT, as Stephan suggested, most of those problems should be fixed in it?
* Which CSS files exactly couldn't be loaded?
* Which error messages are displayed? 
* Could you try to provide a minimal example which allows us to reproduce these problems?

**Comment by nokiajavi** [comment]
Hello, I tested with version 0.8.2 - snapshop , this version does not generate any error loading .CSS or anything. But still does not show the calendar button.

This is the code that makes the button is not shown:
.ui- datepicker -trigger {
    display: none;
}

It is the file that hides the button, is bootfaces css : http://localhost:8080/JSF/javax.faces.resource/css/default/bsf.css.xhtml?ln=bsf

It seems that overrides the CSS of PrimeFaces class .ui -button:
.ui- button {
    display : inline - block;
    position: relative ;
    padding: 0;
    margin-right : .1em ;
    text- decoration: none ! important;
    cursor : pointer;
    text-align : center;
    zoom: 1;
    overflow: visible ;

Example Code:

```
<p:tabView id="tab" effect="fade" effectDuration="fast"  prependId="false" dynamic="true">
  <p:tab id="tabInfo" title="#{text['personaForm.tabInfo']}">
    <b:panelGrid colSpans="2,4,2,4" >
     <h:outputLabel value="#{text['personaForm.inicioPrestacion']}:"/>
     <h:panelGroup>	
      <p:calendar id="inicioPrestacion" value="#{personaForm.fhinipre}"  
         showButtonPanel="true" size="10" showOn="button" navigator="true" 
        locale="# {text['calendar.language']}" 
        mindate="#{personaForm.minDateInicioPrestacion}" 
        maxdate="#{personaForm.maxDateIniPres}" 
        selectOtherMonths="true" pattern="dd/MM/yyyy" readonlyInput="true" 
        label="#{text['personaForm.inicioPrestacion']}" 
        disabled="#{empty personaForm.domicilios or personaForm.puedeCambiarFechaInicio() eq false}">
         <p:ajax event="dateSelect"  update="finPrestacion borrarFechaIni borrarFechaFin" />
       </p:calendar>
       <p:commandButton id="deleteDate"  icon="ui-icon ui-icon-close" title="#{text['button.title.BorrarFechaIniPres']}" action="#{personaForm.borrarFechaIniPres}"
 update="@this inicioPrestacion " 
disabled="#{personaForm.puedeBorrarFechaInicio() eq false}" />
        </h:panelGroup>
..... .....
</b:panelGrid>
```

**Comment by zhedar** [comment]
Did you try PrimeFaces 6.0.RC2 as well? As for as I know, bsf.css should be rendered before primefaces.css, therefore primefaces *should* override some of its settings.
Thanks for the example code, may try to reproduce that if I get to it.

**Comment by nokiajavi** [comment]
With de Primefaces 6.0.RC2 and Bootfaces 0.8.2-SNAPSHOP  Show the following error:
Unable to find resource primefaces, primefaces.css

**Comment by zhedar** [comment]
I had this error as well, turned out, that I included `primefaces.css` in one of my `h:outputStylesheet`s. The [migration guide](https://github.com/primefaces/primefaces/wiki/Migration-Guide) says that it was replaced by `core.css` and `components.css`, so you have to to that as well, if you need it explicitly.

**Comment by nokiajavi** [comment]
Yes, I have PFE 4.0.0 included

**Comment by nokiajavi** [comment]
hello looking at the web boortfaces , I have seen the failure calendar button not shown .
You can check it by going to showcase yourself the page bootsfaces:

http://showcase.bootsfaces.net/integration/PrimeFaces.jsf

I enclose a screenshot so you see today what is happening .
![sin titulo](https://cloud.githubusercontent.com/assets/13865234/16038005/55c88da8-3223-11e6-9d55-09a2b48cebfe.png)


regards

**Comment by stephanrauh** [comment]
Oops, you are right. Thanks for pointing this out! As a fast work-around, you can add this css style:

```html
<style>
.ui-calendar > .ui-datepicker-trigger {
  display:inline;
}
</style>
```html

**Comment by stephanrauh** [comment]
I've fixed this bug in BootsFaces 0.9.0. This version is due very soon - either this weekend or the next weekend. 
You can review the bugfix at our development showcase: http://www3.bootsfaces.net/Showcase/integration/PrimeFaces.jsf.
