### ISSUE TITLE
Unable to save dynamic action with clientId 'j_id...'

### ISSUE THREAD

**Issue by rpinquie** [TheCoder4eu/BootsFaces-OSP#325]
Hi all,

I am getting many warnings as this one "Unable to save dynamic action with clientId 'j_id31' because the UIComponent cannot be found".

Could anyone explain me how to upgrade to OmniFaces 2.2? I do not have explictly specified any OmniFaces dependency, thus I am wondering which one I should modify.

Tanks in advance,

Romain

**Comment by farooq7124** [comment]
Hi,

I am facing same issue with Prime faces. Please update any solution if anyone resolved.

Thanks,
Mohammed Farooq

**Comment by asterd** [comment]
Hi,
can you provide an example that raise this issue? i'm trying to replicate it but without success.. 
About OmniFaces, if you use maven to build your project you have to change the pom.xml to referencing the newest version of OmniFaces, otherwise you can just download the newest jar and put inside your WEB-INF/lib...

**Comment by stephanrauh** [comment]
@rpinquie It's unlikely that you get the error message without activating OmniFaces. Which libraries do you use? Is OmniFaces part of your WEB-INF/lib folder?

**Comment by stephanrauh** [comment]
@farooq7124 This is a warning, not an error. As soon as you set the ProjectStage to production, the warning is gone. So I consider this a minor nuisance, not a serious error. In any case, do you get the warning without using OmniFaces?

**Comment by rpinquie** [comment]
@stephanrauh Actually, OmniFaces is not part of my WEB-INF/lib folder. I was just investigating OmniFaces's solution as you advised me in a previous post.

Before moving to BootsFaces I was using PrimeFaces and never got such warning. Do you think it is maybe be due to the blend of BootsFaces and PrimeFaces?

**Comment by stephanrauh** [comment]
@rpinquie Unlikely. The warning occurs when you manipulate the JSF DOM tree using the wrong API. For instance, by removing a resource file by simply deleting it from the list. That's what OmniFaces used to do in an earlier version. JSF detects that something's missing, gets nervous and reacts with omitting these confusing warnings. It's possible that BootsFaces uses the "forbidden" API, but I believed to have fixed that. In any case, can you upload a simple project that reproduces the warning? This make our job a lot easier.

**Comment by stephanrauh** [comment]
I managed to reproduce the issue with this JSF view:
```xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
  <h:head></h:head>
  <h:body>
    <h:form>
      <b:commandButton />
    </h:form>
  </h:body>
</html>
```

**Comment by stephanrauh** [comment]
Seems like js/bsf.js, jsf.js, css/default/tooltip.css, css/default/core.css and `InternalIE8CompatiblityLinks` are added on each postback.

**Comment by stephanrauh** [comment]
Also see https://java.net/jira/browse/JAVASERVERFACES-2471 and https://github.com/omnifaces/omnifaces/issues/135.

**Comment by stephanrauh** [comment]
Solved the `InternalIE8CompatiblityLinks` bit. It shouldn't have been removed from the resource list at all.

**Comment by zhedar** [comment]
This problem is still around, I could reproduce it with the current master build on several occasions.
Last place, where I found it: Go to http://showcase.bootsfaces.net/forms/commandButton.jsf and press any of the first buttons a couple times.

I went spelunking in the [AddResourcesListener](https://github.com/TheCoder4eu/BootsFaces-OSP/blob/555be75f4134825e43433b87ed073ef718566793/src/main/java/net/bootsfaces/listeners/AddResourcesListener.java) a bit and found, that the warnings may come from `enforceCorrectLoadOrder`.
If I comment out the lines 633 - 662 (the actual removal and adding of components), these warnings don't appear anymore (as far as my tests go, I may check on this on a more appropriate hour of the day).

I'm not sure how this could be handled, but I guess `c.setInView(false);` maybe won't help in this case. Just commenting them out of course isn't the right way ;(

PS: The line numbers are referencing the [linked version](https://github.com/TheCoder4eu/BootsFaces-OSP/blob/555be75f4134825e43433b87ed073ef718566793/src/main/java/net/bootsfaces/listeners/AddResourcesListener.java) of the file in case it gets updated meanwhile.

**Comment by stephanrauh** [comment]
Should be fixed by now. Running the final tests.

**Comment by zhedar** [comment]
Great news! Will test when I'm home again.

**Comment by zhedar** [comment]
I just stumbled upon another case of this in the `/forms/selectOneMenu.jsf` showcase. It get's triggered after the second ajax request. Somehow, another `jsf.js` resource is added, so we end up with 2 and the first gets removed. However, it isn't added in `addResourceIfNecessary`. So it gets added elsewhere...

On the way I've removed some old spots where bsf.js and jsf.js were added in the components directly, but these weren't the cause.

**Comment by zhedar** [comment]
I found a quick fix for it: The new jsf.js was added at the top of the head, therefore the first one was always removed. We need to sort the resources list by clientid, before we remove the duplicated resource. This way the freshly added duplicated will get removed and not the first file. It's still not the best solution, because resources shouldn't be duplicated in the first place, but it may be viable until we find the real source.

**Comment by zhedar** [comment]
Seems like my quick fix did more harm than it cured. Somehow it spawned many warnings, when PrimeFaces was used. Somehow it adds 5 files in every request, which get duplicated. this way. This is somewhat suboptimal, because the clientids get abtrusively high this way. Removing the new files creates the warnings, don't ask me why. I may have a look at their HeadRenderer next.

**Comment by traxtech** [comment]
Hi.

I had this issue or a very similar one with "Unable to save dynamic action with clientId...", and disabling JSF partial state saving in web.xml did the trick:

<context-param> 
        <param-name>javax.faces.PARTIAL_STATE_SAVING</param-name> 
        <param-value>false</param-value> 
</context-param>

Hope it helps!

**Comment by zhedar** [comment]
@traxtech I wouldn't recommend disabling State Saving just to get rid of the warning. (Or if you don't trust me, [look at Bauke Scholtz](http://stackoverflow.com/a/10337452/1644440).)

If you want to get rid of it in your production environment, I would recommand to set the project stage to production instead. This way the warning won't appear in the production logs.

**Comment by traxtech** [comment]
Interesting read, thanks!

**Comment by zhedar** [comment]
I'm finally going to reopen this issue, as I spent my whole day tracking a nasty bug. It ended right on my quick fix, which was the obvious cause. Reordering the resources isn't the right way, atleast it produced some weird PrimeFaces-related javascript errors for me for the last releases. So I'm going to remove it again.

I'm sure I was there quite some times before, but I will write it down right here (again?):
Our way of reordering the resources (`enforeCorrectLoadOrder`) is causing the duplicated PrimeFaces resources. If we disable that, the duplicated files are gone. I'm not sure, if there is a way to exclude those resources, but that would be my first way to go. (So we reordner everything but those resources, but then again we couldn't place our resources before them. But would we even need to?)

I also checked the PrimeFaces showcase's poll example. The default seems to be, that PrimeFaces' resources are added on every request, but somehow they don't they there. On the next request they will have another client_id. This leads to steadily incrementing ids. I have no idea, if this may have any impact on long running, often polling applications.
Maybe I can summon @tandraschko, so I might get some insight, why this happens. Does the `HeadRenderer` only add them temporarily, so they don't end up staying in the component tree?

**Comment by tandraschko** [comment]
Summon? Sounds like i'm a bad demon or something :D
Maybe you could introduce the bug for me in some sentences?

We have 2 things regarding resources:
1) HeadRenderer
    it renders dynamically/temporarily some files because they are not directly related to components:
    - theme
    - fontawesome
    - client side validation scripts
    There are never references by any components are not available as component resources in the UIViewRoot

2) dynamic resource laoding
    In JSF, when you add a component dynamically via postback, the component resources are not available on the client because JSF doesn't add them dynamically
    In PrimeFaces, we listen if new resources are added to the viewroot and render some scripts to load them.

**Comment by tandraschko** [comment]
AND:
I fixed many minor bugs about 2) in trunk some weeks ago. So please try with trunk.

**Comment by zhedar** [comment]
>Summon? Sounds like i'm a bad demon or something :D  

Well it worked, didn't it? I also sacrificed a Wolpertinger just to be sure.

I just tried it the latest 6.1-SNAPSHOT from master, but the problem still persisted. Also the showcase version I tested this on is the latest and uses 6.1. So it actually is caused by us (atleast partly from what I know).

**The problem is the following:**
We have a resource reordering mechanism (just like the one from PrimeFaces), which removes and adds resources from the view root. This happens in [enforceCorrectLoadOrder](https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/java/net/bootsfaces/listeners/AddResourcesListener.java#L559).
Therefore the resources may be in a different place afterwards, as we're adding our own css in front so that all other resources can overwrite them if needed.

So, if you're saying, you are listening to new resources being added, where exactly does that take place? May we confuse your system by mixing up the resources and therefore spawn many duplicated files?

Also these bugs almost never occur on the first request, so 2) seems to be related more then 1) for me.

**Comment by tandraschko** [comment]
:D

Nope, AFAIR we never modify the resources on the server side. We also don't add resources to the viewroot via #addComponentResource.
We just do a diff on the resources in the viewroot on RESTORE_VIEW and before RENDER_VIEW. With the result, we render scripts to load the js/css on the client. Everything happens readonly.

You said something thats wrong in our showcase. Does it occur without BootsFaces, too? Whats the problem exactly?

**Comment by zhedar** [comment]
The actual problem of duplicated resources doesn't happen in your showcase, but the root of the problem is the changing ids of the resources there. If I monitor the resources (via  `FacesContext.getCurrentInstance().getViewRoot().getComponentResources(context, "head")) and execute the poll example, it results in this:

	**new request**
	j_idt5 main/css/showcase.css null UIOutput
	j_idt6 main/css/perfect-scrollbar.css null UIOutput
	j_idt7 main/css/sh.css null UIOutput
	j_id2 jquery/jquery.js primefaces UIOutput
	j_id3 jquery/jquery-plugins.js primefaces UIOutput
	j_id4 core.js primefaces UIOutput
	j_id5 components.css primefaces UIOutput
	j_id6 components.js primefaces UIOutput
	**new request**
	j_id7 jquery/jquery.js primefaces UIOutput
	j_id8 jquery/jquery-plugins.js primefaces UIOutput
	j_id9 core.js primefaces UIOutput
	j_id10 components.css primefaces UIOutput
	j_id11 components.js primefaces UIOutput
	j_idt5 main/css/showcase.css null UIOutput
	j_idt6 main/css/perfect-scrollbar.css null UIOutput
	j_idt7 main/css/sh.css null UIOutput
	**new request**
	j_id12 jquery/jquery.js primefaces UIOutput
	j_id13 jquery/jquery-plugins.js primefaces UIOutput
	j_id14 core.js primefaces UIOutput
	j_id15 components.css primefaces UIOutput
	j_id16 components.js primefaces UIOutput
	j_idt5 main/css/showcase.css null UIOutput
	j_idt6 main/css/perfect-scrollbar.css null UIOutput
	j_idt7 main/css/sh.css null UIOutput

So it only happens to the javascript files in there.

I haven't tried to include BootsFaces in the showcase yet, but will do that now.

**Comment by tandraschko** [comment]
I see but we don't influence that. AFAIK in plain PrimeFaces case, its just up to the JSF impl.

**Comment by stephanrauh** [comment]
This bug is also covered by #365. I'll close this bug in favor of the other bug.

**Comment by myhtls** [comment]
My environment is wildfly10, jdk8, primefaces6, omnifaces2.6, bootsFaces1.0.1
All the commandButton are not easy to use, can not call the actionListener background bean method, sometimes infinite exception.

my web.xml:

<context-param>
        <param-name>BootsFaces_THEME</param-name>
        <param-value>yeti</param-value>
    </context-param>
    
    
    <context-param>
        <param-name>BootsFaces_USETHEME</param-name>
        <param-value>true</param-value>
    </context-param>
    
    <context-param>
      <param-name>net.bootsfaces.blockUI</param-name>
        <param-value>true</param-value>
    </context-param>
    <context-param>
      <param-name>net.bootsfaces.defaults.renderLabel</param-name>
        <param-value>false</param-value>
    </context-param>
    <context-param>
      <param-name>net.bootsfaces.defaults.decorator</param-name>
        <param-value>false</param-value>
    </context-param>
	
	

	

	
	<context-param>
		<param-name>org.omnifaces.COMBINED_RESOURCE_HANDLER_EXCLUDED_RESOURCES</param-name>
		<param-value>bsf:css/icons.css</param-value>
	</context-param>

	<context-param>
		<param-name>org.omnifaces.VIEW_SCOPE_MANAGER_MAX_ACTIVE_VIEW_SCOPES</param-name>
		<param-value>15</param-value>
	</context-param>

	<context-param>
		<param-name>org.omnifaces.EXCEPTION_TYPES_TO_UNWRAP</param-name>
		<param-value>javax.ejb.EJBException,javax.persistence.RollbackException</param-value>
	</context-param>
	
	<context-param>
		<param-name>javax.faces.FACELETS_LIBRARIES</param-name>
		<param-value>/META-INF/nature.taglib.xml</param-value>
	</context-param>
	


	
	

	<context-param>
		<param-name>primefaces.CLIENT_SIDE_VALIDATION</param-name>
		<param-value>true</param-value>
	</context-param>

	<context-param>
		<param-name>primefaces.UPLOADER</param-name>
		<param-value>commons</param-value>
	</context-param>

	<context-param>
		<param-name>primefaces.FONT_AWESOME</param-name>
		<param-value>true</param-value>
	</context-param>

	<context-param>
		<param-name>primefaces.TRANSFORM_METADATA</param-name>
		<param-value>true</param-value>
	</context-param>

	



	
	<context-param>
		<param-name>javax.faces.FACELETS_BUFFER_SIZE</param-name>
		<param-value>65535</param-value>
	</context-param>


	<context-param>
		<param-name>javax.faces.STATE_SAVING_METHOD</param-name>
		<param-value>server</param-value>
	</context-param>

	<context-param>
		<param-name>javax.faces.DATETIMECONVERTER_DEFAULT_TIMEZONE_IS_SYSTEM_TIMEZONE</param-name>
		<param-value>true</param-value>
	</context-param>

	<context-param>
		<param-name>javax.faces.DEFAULT_SUFFIX</param-name>
		<param-value>.xhtml</param-value>
	</context-param>
	<context-param>
		<param-name>javax.faces.FACELETS_SKIP_COMMENTS</param-name>
		
		<param-value>true</param-value>
	</context-param>
	<context-param>
		<param-name>javax.faces.PROJECT_STAGE</param-name>
		
		<param-value>Development</param-value>
	</context-param>



	<filter>
		
		
		<filter-name>characterEncodingFilter</filter-name>
		<filter-class>org.omnifaces.filter.CharacterEncodingFilter</filter-class>
	</filter>

	<filter-mapping>
		<filter-name>characterEncodingFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>

	<filter>
		<filter-name>gzipResponseFilter</filter-name>
		<filter-class>org.omnifaces.filter.GzipResponseFilter</filter-class>
		<init-param>
			<description>The threshold size in bytes. Must be a number between 0 and 9999. Defaults to 150.</description>
			<param-name>threshold</param-name>
			<param-value>150</param-value>
		</init-param>
		<init-param>
			<description>The mimetypes which needs to be compressed. Must be a commaseparated string. Defaults to the below values.</description>
			<param-name>mimetypes</param-name>
			<param-value>
                text/plain, text/html, text/xml, text/css, text/javascript, text/csv, text/rtf,
                application/xml, application/xhtml+xml, application/javascript, application/json,
                image/svg+xml
            </param-value>
		</init-param>
	</filter>

	<filter-mapping>
		<filter-name>gzipResponseFilter</filter-name>
		<servlet-name>FacesServlet</servlet-name>
		<dispatcher>REQUEST</dispatcher>
		<dispatcher>ERROR</dispatcher>
	</filter-mapping>



	<filter>
		<filter-name>FileUploadFilter</filter-name>
		<filter-class>org.primefaces.webapp.filter.FileUploadFilter</filter-class>
		<init-param>
			
			<param-name>thresholdSize</param-name>
			<param-value>51200</param-value>
		</init-param>
		
	</filter>
	<filter-mapping>
		<filter-name>FileUploadFilter</filter-name>
		<servlet-name>FacesServlet</servlet-name>
	</filter-mapping>


	<filter>
		<filter-name>facesExceptionFilter</filter-name>
		<filter-class>org.omnifaces.filter.FacesExceptionFilter</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>facesExceptionFilter</filter-name>
		<servlet-name>FacesServlet</servlet-name>
	</filter-mapping>
	
	<servlet>
		<servlet-name>FacesServlet</servlet-name>
		<servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
		<load-on-startup>1</load-on-startup>
	</servlet>
	<servlet-mapping>
		<servlet-name>FacesServlet</servlet-name>
		<url-pattern>*.xhtml</url-pattern>
	</servlet-mapping>
.my xhtml:

<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:b="http://bootsfaces.net/ui">
<h:head>

	<title>注册</title>
	<h:outputScript name="js/datepicker-zh.js" />

</h:head>
<h:body>
<h:form id="formId" >
	<b:container>
		
		
			<b:growl id="growlMsg" globalOnly="true" placementFrom="bottom"
				show-detail="true" show-summary="false" allowDismiss="true"
				delay="10000" escape="true" />

			<b:panel title="注册用户" collapsible="false">
				<b:inputText value="#{driverQuery.udriver.userName}" id="phoneId"
					placeholder="请填写手机号." required="true" requiredMessage="必须填写手机号." 
					 validatorMessage="手机号必须是11位.">
					<f:validateLength minimum="11" maximum="11" />
					<f:facet name="prepend">
						<b:iconAwesome name="phone" />
					</f:facet>
				</b:inputText>
				
				<b:inputSecret value="#{driverQuery.udriver.password}"   id="passwordId"
				validatorMessage="密码不能低于6位高于20位"
					placeholder="请填写密码" required="true" requiredMessage="必须填写密码.">
						<f:validateLength minimum="6" maximum="20" />
					<f:facet name="prepend">
						<b:iconAwesome name="key" />
					</f:facet>
				</b:inputSecret>

				<b:inputText value="#{driverQuery.udriver.name}" 
				 id="nameId"
				placeholder="请填写姓名" required="true" requiredMessage="必须填写姓名." required-message="必须填写姓名." >
				<f:facet name="prepend">
						<b:iconAwesome name="leaf" />
					</f:facet>
				</b:inputText>
				
				
				
				<b:selectOneMenu value="#{driverQuery.udriver.sex}" id="brandID" >
					<f:selectItem itemLabel="性别" itemValue="" />
					<f:selectItem itemLabel="男" itemValue="1" />
					<f:selectItem itemLabel="女" itemValue="2" />
					<f:facet name="prepend">
						<b:iconAwesome name="male" />
					</f:facet>
				</b:selectOneMenu>
				
				<b:inputText value="#{driverQuery.udriver.card}"  id="cardId"
					placeholder="请填写身份证">
					<f:facet name="prepend">
						<b:iconAwesome name="id-card-o" />
					</f:facet>
				</b:inputText>
				
				<b:inputText value="#{driverQuery.udriver.mail}"  id="mailId" placeholder="请填写邮件">
					<f:facet name="prepend">
						<b:iconAwesome name="at" />
					</f:facet>
				</b:inputText>

				<b:dateTimePicker placeholder="生日"  id="birthdayId"
				format="yyyy-MM-dd" show-date="true" 
					value="#{driverQuery.udriver.birthday}" >
					<f:facet name="prepend">
						<b:iconAwesome name="at" />
					</f:facet>
					</b:dateTimePicker>

				<f:facet name="footer">
					<b:commandButton value="注册" update="@form"  ajax="true" process="@form" actionListener="#{driverQuery.testAction()}"  />
					<p:commandButton  value="注册" update="@form" actionListener="#{driverQuery.testAction()}"   process="@form"  />
				</f:facet>
			</b:panel>
			

			
	
		</b:container>
			</h:form>
</h:body>
</html>
