### ISSUE TITLE
Messages showDetail has wrong default value and shows summary twice

### ISSUE THREAD

**Issue by zhedar** [TheCoder4eu/BootsFaces-OSP#352]
The documentation states, that `showDetail` should be `false`, but the real value is `true`.
Therefore currently the summary message will be shown twice at the moment, if no detail is provided as 
[StackOverflow user b.lopes reports](http://stackoverflow.com/q/36829941/1644440).

This probably shouldn't happen at all, maybe we should opt for not showing a detail, if it's value is `null`.

I have not checked this, but the same may apply to the growl.

**Comment by stephanrauh** [comment]
I've corrected the default values in the jsfdsl file. Three components are affected: b:message, b:messages and b:growl.

**Comment by zhedar** [comment]
Thanks, I had that sitting in my trunk but didn't get to it yet. What do you think about checking the detail for null additionally to just checking showDetail?

**Comment by stephanrauh** [comment]
Actually, I don't get it. Why is the summary shown twice if the detail is null? Looking at the code, I'd expect either nothing or the text "null":

```java
				if (message.isShowDetail()) {
					rw.startElement("span", component);
					writeAttribute(rw, "class", "bf-message-detail");
					if (message.isEscape()) {
						rw.writeText(msg.getDetail(), null);
					} else {
						warnOnFirstUse();
						rw.write(msg.getDetail());
					}
					
					rw.endElement("span");
				}
```

**Comment by zhedar** [comment]
Did you verify the bug in the current snapshot though?

I remember, that PrimeFaces' growl had (or has?) the same issue. Maybe UI-message thats detail = summary, if detail is null?

**Comment by asterd** [comment]
This bug was solved by the cc35075 commit.
Can you test it to check if now is all ok?

**Comment by stephanrauh** [comment]
I've changed the default value back to "true". Suppressing the details of an error message by default seems to be a bit odd. However, I've corrected the documentation.

**Comment by zhedar** [comment]
@stephanrauh Saw that, just wanted to write that we may need a fix for the original problem now again:
<img width="932" alt="bildschirmfoto 2016-04-29 um 23 23 18" src="https://cloud.githubusercontent.com/assets/6633403/14930079/9ce16b6e-0e61-11e6-9b92-5a1bbcc3370a.png">
Taken from the [showcase](http://www3.bootsfaces.net/Showcase/forms/messages.jsf). Seems like the infamous icons.css bug is back again, I just don't know why yet.

However, I may have an idea considering the double messaged, will test that now.

**Comment by stephanrauh** [comment]
Actually, I prefer duplicate message over no messages. But I agree with you that we should avoid these duplicate messages. They are a standard behavior of JSF, but that's no excuse: we've founded BootsFaces to make the JSF world a better place :).

**Comment by stephanrauh** [comment]
The duplicate message shows only after a full-page request (F5 key). Plus, the "icons" message doesn't pop up on my local installation.

**Comment by zhedar** [comment]
As I have mentioned, I couldn't reproduce the icons.css bug as well. However the initial messages show only once for me, refreshing the page via cmd + R doesn't work, neither in Safari nor Chrome, although the cache is disabled. I didn't figure out, why this is yet. Therefore this is currently quite hard to reproduce for me.

**Comment by zhedar** [comment]
The problem should be fixed my now.  
Now we don't really need the user to set `showSummary` or `showDetail` explicitly, It should always be rendered correctly. If only a summary is provided, I stayed with our current implementation: Show it as a detail, because if there is only a single message, we don't need to format that bold, it looked a bit weird. If only a detail is provided, the text won't be indented anymore.

**Comment by stephanrauh** [comment]
That's great news! Unfortunately, the showcase still shows the "icons.css" messages on first load:
![image](https://cloud.githubusercontent.com/assets/3045767/14938138/d88a7232-0f1a-11e6-8504-205627b54d98.png)
I've tested it with Google Chrome on OS X (but I'm sure it's not a browser problem).

**Comment by zhedar** [comment]
@stephanrauh I found reason for this to happen: We're both using the maven build. However, the gradle build doesn't remove resources from the `mavenResources` folder, it will only replace existing ones.
So somehow the gradle build changed and icons.css won't get copied into the theme folders anymore and is therefore missing in the showcase.
