### ISSUE TITLE
Broken components after the latest pushes

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#357]
* ~~b:slider (Layout problems - horizontal slider bar too wide?)~~
* ~~b:tree (JavaScript errors)~~
* ~~b:scrollSpy (missing JavaScript resource)~~
* ~~AJAX demo (forms/ajax.jsf) doesn't update the list of server events~~
* AJAX demo (forms/ajax.jsf) the comboboxes flicker when opened
* ~~forms/commandButton.jsf: the "AJAX modal" button shows old input. Maybe it doesn't use partial processing?~~
* ~~several `b:message` demos show empty messages. Probably that's due to the change of the default value of `showDetail`.~~
* ~~The message details of forms/messages.jsf are missing.  Probably that's due to the change of the default value of `showDetail`.~~
* ~~The last demo of forms/selectOneMenu.jsf behaves a bit odd. The car brand is always cleared after selecting a car type.~~
* The components we've introduced with version 0.8.2 should have a "since 0.8.2" badge in the showcase. Examples: `b:canvas`, `b:accordion`.
* ~~The PrimeFaces demo pages shows the error message "Unable to find resource bsf, css/journal/bootstrap-treeview.min.css" with the "journal" theme~~
* The ButterFaces integration demo is broken. The autocomplete doesn't offer autocomplete suggestions. The JavaScript console shows JS errors.

**Comment by TheCoder4eu** [comment]
b:slider - at first glance, seems a columns rendering problem; vertical Sliders seem unaffected

**Comment by asterd** [comment]
b:slider and b:column problems were solved. For slider is a wrong default value for span and for column is the addition of long-name properties in jsfdsl file (eg. medium-screen): in this way BsfBeanInfo addAlternativeForScreenLayout does not work anymore.. so the management of multiple definition is done inside the column renderer (maybe, in the future, we have to decide or to drop long-name attributes or to migrate the new method inside columnRenderer to the CoreRenderer)

**Comment by asterd** [comment]
Also b:messages is resolved with my yesterday commit.
about b:scrollspy i've tested and i don't see javascript missing resource.. do you still have this problem? same thing for b:tree.

I've also updated the showcase to add 0.8.2 ref on new components.

**Comment by stephanrauh** [comment]
@asterd  THX for fixing these bugs! But the scrollspy problem is still there:
```
WARNUNG: JSF1064: Ressource js/scrollspy.js aus Bibliothek bsf kann nicht gefunden oder bedient werden.
```
Actually, there's no scrollspy.js in my project. Into which folder did you put it?

**Comment by stephanrauh** [comment]
@asterd Just an idea: do you use the Gradle build? I wonder if the Maven resource folder is missing a couple of files. That might explain why the tree does work in our showcase (based on Gradle), but not on my local PC (running on Maven).

**Comment by zhedar** [comment]
@stephanrauh. Running gradle should fix this indeed, because that resource was recently added.

**Comment by stephanrauh** [comment]
@zhedar @asterd @TheCoder4eu  That was a huge quantity of files I've missed. Please keep the MavenResources folder up-to-date after adding a resource using the Gradle build. Thanks!

**Comment by zhedar** [comment]
It's mostly because @TheCoder4eu recently added all bootswatch themes in 5432b7d3cca11b3ab13659575390469dbb9ba928, atleast that's why it looked so big. You were probably only missing 1 or 2 new files.  
I didn't want to stuff those files in the PR, and make it even more bigger ;)

**Comment by asterd** [comment]
You are right.. I have supposed that you do a gradle build to align the mavenResources! So, apart from this, remains only few problems to solve about this issue isn't it?

**Comment by stephanrauh** [comment]
Well, I haven't figured out how to publish to Maven Central using Gradle. Plus, I think it's a good strategy to support both Maven and Gradle, because some developers prefer one tool, others prefer the other tool. But I was lazy and didn't implement the entire workflow in the Maven build. It depends on the Gradle build to generate the resource files. These files are version in the MavenResources folder, so friends of Maven simply download the resources when cloning the repo. The disadvantage of this approach is that every once in a while someone forgets to add a resource file. In general, this is not a big deal, but this time I simply didn't expect this kind of error, which left me puzzled :).
