### ISSUE TITLE
wrong style in navbar 0.8.5.

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#374]
Hello All,

When I try to update to 0.8.5. the navbars rendered incorrectly. It looks like the styles are missing. My last used version is 0.8.1.

Thank you,
Mihaly

**Comment by asterd** [comment]
@lyahim yes, you were right. We have already found this bug and also solved it in 0.8.6 branch (f1b5ebe). We hope to release a fix version asap!

**Comment by stephanrauh** [comment]
@asterd You say this issue has been solved in 0.8.6? If so, feel free to close the issue.

**Comment by lyahim** [comment]
Hello All,

Please reopen the ticket, because not fixed yet.

Thank you,
Mihaly

**Comment by asterd** [comment]
Hi @lyahim, can you send a screenshot of the style problem?

**Comment by lyahim** [comment]
Hello asterd,

I attached. I hope successfully

Mihaly
![navbar_good](https://cloud.githubusercontent.com/assets/3195083/15543686/27965c5e-2296-11e6-89d3-bcd7b25ae1ac.PNG)
![navbar_wrong](https://cloud.githubusercontent.com/assets/3195083/15543687/279690e8-2296-11e6-9acb-1dbfb7eb1fd3.PNG)

**Comment by lyahim** [comment]
I checked the navbar.css and looks like same the old and the new one. But in rendered code I see the li changed some place to span.

**Comment by lyahim** [comment]
Hello All,

Is there any news?

Thank you,
Mihaly

**Comment by TheCoder4eu** [comment]
@lyahim you did try this with 0.8.6 too, did you?

**Comment by stephanrauh** [comment]
I suppose your problem are caused by #310. A solitary `<b:navLink />` is now rendered as a `<span>` instead of a `<div>`. I wonder why your menu items are considered solitary navLinks by BootsFaces? What does your JSF code look like? `<b:navLink />` should be in one of the following containers:
* DropButton
* NavBar
* TabLinks
* PillLinks
* NavBarLinks
* DropMenu
* FlyOutMenu
Otherwise, they are rendered as `<span>`.

**Comment by TheCoder4eu** [comment]
If Mihaly still has problems we should open a new issue on 0.9.0 and keep closed this one.
