### ISSUE TITLE
b:datatable is duplicating itself when not in view

### ISSUE THREAD

**Issue by MitchTalmadge** [TheCoder4eu/BootsFaces-OSP#440]
I seem to have found an extremely weird bug with b:datatable. When I create a b:datatable and have a lot of content on my page so that I can scroll to where only half or less of the datatable is showing, then if I use ajax to re-render the container that contains the datatable, I find tons of duplicate tables at the bottom of the screen. Additionally, sometimes I get error messages.

Here is an example:

Here is my page, with a datatable and some content on the screen which creates a scrollbar:
![image](https://cloud.githubusercontent.com/assets/8848080/16397166/f07b25e8-3c7f-11e6-89c1-7c9b86b971b5.png)

Notice the HTML of this page:
![image](https://cloud.githubusercontent.com/assets/8848080/16397220/4acc7a92-3c80-11e6-9e9e-4f14fc6a62dc.png)

Now let's scroll down, a bit past the datatable:

![image](https://cloud.githubusercontent.com/assets/8848080/16397236/66ad3508-3c80-11e6-907b-5a4799398f3a.png)

This is the minimum amount of scrolling that needs to be done to trigger the problem, right above the text of the first row.

Take a look at the HTML now:
![image](https://cloud.githubusercontent.com/assets/8848080/16397258/8c3d654a-3c80-11e6-8fb6-dde22126b271.png)

Where did all that come from? It disappears if I scroll back up. If I am to re-render the part of the page that contains the datatable while these are in the HTML, this happens:

![image](https://cloud.githubusercontent.com/assets/8848080/16397286/ac99444e-3c80-11e6-8a8a-145130dfcec2.png)

If I now re-render the part of the page again, after these have appeared, I get one of these errors for every table, and an additional table is created:

![image](https://cloud.githubusercontent.com/assets/8848080/16397321/e4a32b2a-3c80-11e6-8e7e-72ec141ac20d.png)

I am on 0.8.6

Thanks!

**Comment by MitchTalmadge** [comment]
It appears that a new table is generated every time the part of the page it is on is re-rendered. Sounds almost like the situation with b:poll where you need to set it to only run once or it will duplicate itself and spam with requests, except in this case the table is being generated every time the page is re-rendered.

**Comment by stephanrauh** [comment]
Yes, updating the datatable with AJAX forces it to be re-initialized. It's very difficult to do better (at least if you're a JSF library provider who has to think of every possible constellation). Maybe it helps to destroy the datatable before calling the AJAX method. BootsFaces doesn't know when this is necessary, so you have to do it manually. I did this in the "Customizing the table" example of http://www3.bootsfaces.net/Showcase/forms/DataTable.jsf (sourcecode at https://github.com/TheCoder4eu/BootsFacesWeb/blob/master/src/main/webapp/forms/DataTable.xhtml).

It also may help to switch to 0.9.0-SNAPSHOT. I'm not sure, but I've modified the DOM tree of several components recently in order to fix AJAX behaviour, possibly include the datatable.

**Comment by zhedar** [comment]
@stephanrauh That may explain, why I couldn't reproduce this in the Showcase with the current dev snapshot. @MitchTalmadge Maybe you should give the snapshot a try and tell us, if it is already fixed.

**Comment by MitchTalmadge** [comment]
Sure thing, I will try it :)

**Comment by MitchTalmadge** [comment]
The 0.9.0-SNAPSHOT does not solve the problem. I am trying to make the destroy work. I'll let you know if I make it work or not.

**Comment by zhedar** [comment]
Have you tried another 0.9.0 Snapshot build before? You may need to remove it from your local m2 repo directory so that it actually updates. Or did you build it yourself via mvn clean install?

**Comment by MitchTalmadge** [comment]
This was the first time I've ever used 0.9.0-SNAPSHOT, so I assume maven got the latest one.

**Comment by MitchTalmadge** [comment]
I discovered that the problem only occurs if fixedHeader is set to "true". Destroying the table did not solve the problem, however setting fixedHeader to false and using the exact same buttons as I was using in the beginning works perfect. This explains why the "Customizing the table" example doesn't have this problem -- fixedHeader is never set to true on it.

**Comment by zhedar** [comment]
This is a problem, I've experienced with PrimeFaces' stickyHeader for a long time as well. They still haven't managed to fixed it though, so I'm currently not sure, if this is that easy to fix. (Aren't we using the same datatables implementation?) However, I can't find their issue right now, maybe it doesn't even exist yet.

**Comment by stephanrauh** [comment]
Actually, our datatable implement is very different from the PrimeFaces implementation. I was very reluctant to implement the datatable because I didn't want to simply copy PrimeFaces. That why our datatable is rendered on the client (at least the decorators and the user interactions), while the PrimeFaces datatable is mostly rendered on the server.

**Comment by stephanrauh** [comment]
I've added the `fixedHeader` option to the demo. I start to believe that `fixedHeader` is broken in the underlying DataTables.net widget. I wonder if we should deactivate the feature?

**Comment by MitchTalmadge** [comment]
Honestly I had forgotten that I even enabled it. It doesn't work for me because I have a fixed header of my own (the navbar) at the top of the screen, which covers the fixed header of the datatable. I personally don't ever plan to use the feature.

**Comment by TheCoder4eu** [comment]
@stephanrauh if it is a bug of the DataTables.net library we could check if they fixed it in the meantime...

**Comment by TheCoder4eu** [comment]
@stephanrauh , I just updated datatables.net from v1.10.12 to v1.10.13 , do you notice any improvements?

**Comment by TheCoder4eu** [comment]
@MitchTalmadge , @stephanrauh : I did try to reproduce the issue, I also scrolled our showcase page but noticed nothing strange.
Could you have a look too to see inf the new version of Datatables + BootsFaces did solve the issue?

**Comment by stephanrauh** [comment]
@MitchTalmadge I know you've abandoned JSF in the meantime, but maybe you can help us with a reproducer? Otherwise, I suggest we close the issue. It feels like chasing shadows.

**Comment by MitchTalmadge** [comment]
I'll try to reproduce it if I can. Since I've moved away from JSF (and WildFly in general) I'll need to see if I can dig up a project to test with

**Comment by stephanrauh** [comment]
@MitchTalmadge THX!

BTW, an important part of the BootsFaces mission is to make JSF simpler. IMHO, JSF can learn a lot from Angular. Do you have any suggestions which ideas JSF can adopt from Angular? Maybe there are even low-hanging fruits?

**Comment by MitchTalmadge** [comment]
I think by far the biggest problem I faced with JSF was that I had no idea how to make my own components. It seemed very difficult. In comparison, Angular makes it very easy and more organized. Instead of building the html within the code, I can put all of it into a separate .html file. Additionally, the css offers encapsulation, allowing me to keep my css organized with my components without worrying about it affecting other components, rather than shoving all of my css into a single file in the root of my application and working tirelessly to make sure there are no conflicts.

The other thing that Angular offers which convinced me to switch was how incredibly easy it was to make single page applications with live on-screen changes. While you could add ajax to many JSF components, it was tedious and there were a lot of components which did not play well with ajax. In angular, you can just put a variable onscreen like `{{counter}}` and as the variable changes, so will the on-screen html. It seriously couldn't be easier.

And lastly, I think I prefer client side rendering to server side. One thing I do miss from JSF was the fact that you never had to make any REST interfaces, and the client and server communicated easily with each other; however, building a REST interface for my application will benefit me in the long run when we create Android/iOS applications and potentially let other developers create extensions of our platform, something that just isn't doable with JSF.

**Comment by TheCoder4eu** [comment]
@MitchTalmadge , 
every technology has its pro and cons... btw are you speaking of Angular1 or 2 or both?
From what you say my Idea to build a JSF framework based on W3C Web Components:

https://www.webcomponents.org
and
www.w3.org/wiki/WebComponents/

would not be a bad Idea... it offers many things you mentioned out of the box and is getting support form all browsers now.

I'll close this Issue for now, please reopen it in case you are still able to reproduce the problem.

**Comment by stephanrauh** [comment]
@MitchTalmadge I was so busy last week I forget to thank you for the analysis. But it proved to be useful in my Angular course. Thanks!
