### ISSUE TITLE
datatable not saving the selected state

### ISSUE THREAD

**Issue by ErickPezoa** [TheCoder4eu/BootsFaces-OSP#796]
I am using primefaces wizard where I have different tabs. To go from one tab to the other, the user has to select a row from the datatable below. Say the user selected a row from the datatable and clicked next but some validations failed when the user clicked the NEXT button on the wizard. When the system comes back, the row is not selected even though the bean var="afi" has data. Is this a bug or am I doing something wrong? Is there any way for the datatable to save the selected state if the bean has data?

```xml
<b:panel id="panelTable" title="Lista de Afiliados" look="primary">
	<p>Seleccione un Afiliado haciendo click en una de las filas.</p>

	<b:dataTable id="afiliadoTable" var="afi" paginated="true"
		value="#{mainController.afiliados}" widgetVar="afiliadoTable"
		lang="es" page-length="5" page-length-menu="5,10,20"
		scroll-size="400px" scroll-x="false" responsive="true" select="true"
		searching="true" striped="true" ajax="true" selectionMode="single"
		saveState="true" info="false"
		onselect="ajax:mainController.onRowSelect(afi);"
		update=":wizard:panelAfiliado">

		<b:dataTableColumn value="#{afi.afiliado_id}" label="Afiliado" />
		<b:dataTableColumn value="#{afi.nombre}" label="Nombres" />
		<b:dataTableColumn value="#{afi.apellido}" label="Apellidos" />
		<b:dataTableColumn value="#{afi.telefono}" label="Tel&#233;fono" />
	</b:dataTable>
</b:panel>

```

**Comment by stephanrauh** [comment]
You've discovered the flag `save-state`, so I guess the problem is caused by redrawing the table from scratch when the page is rendered. It looks like a duplicate of #836. Currently, there's no way to tell the table which row is selected from the server side.

**Comment by stephanrauh** [comment]
In the meantime, I've implemented a way to select the row (or column or cell) from the server side. See http://www3.bootsfaces.net/Showcase//forms/DataTable.jsf#selecting for more details.

**Comment by ErickPezoa** [comment]
@stephanrauh I clicked on the link but it seems like the page is not working. I am still having the issue I presented on this ticket. Any help much appreciated.

**Comment by stephanrauh** [comment]
@ErickPezoa In the meantime, we've published BootsFaces 1.2.0, so the link is available in the official documentation page: https://showcase.bootsfaces.net/forms/DataTable.jsf#selecting

**Comment by stephanrauh** [comment]
@ErickPezoa Please report back if this solves your problem. If not, feel free to reopen the ticket.
